spring:
  datasource:
    url: jdbc:mariadb://localhost/mariadb
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: alsd7856
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: crate

